name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create archive
        run: |
          zip -r rkn-hardening-${GITHUB_REF_NAME}.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: rkn-hardening-${GITHUB_REF_NAME}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
